### ISSUE TITLE
A APIC Drupal Hook IS causing Error

### ISSUE THREAD

**Issue by shuhaibofficial** [ibm-apiconnect/devportal#8] opened 2020-03-04 11:54 UTC
**APIC Version**: 2018.X
**Drupal Version**: 8.x
**My Goal** : Try to Invoke a Drupal 8 Hook which is provided by IBM APIC .
**Issue Occurred** in  Developer Portal When a subscription is made.
**Hook Name**: hook_apic_app_subscribe
**Erorr** : The website encountered an unexpected error. Please try again later
Custom Module Link or code: [Download](https://developer.ibm.com/answers/storage/temp/30628-send-sub-data.zip)
- **What I have Done** : 
      Created a custom module as per the Drupal 8 Requirements 
       my custom module name: _send_sub_data_
       Modules Directory Structure:
            **send_sub_data** -- **Module name** 
                      send_sub_data.info.yml
                      send_sub_data.module

**File send_sub_data.info.yml**
`name: Send and View Payment Information v2
description: This Custom Module Involkes When A Subscription made by AN App.
package: Custom
type: module
version: 1.0
core: 8.x`

**File send_sub_data.module** 
`<?php
function send_sub_data_apic_app_subscribe(NodeInterface $node, $data, $appId, $product_url, $plan, $subId) {
    //Do nothing 
}`

Note:
I have created custom module in Drupal 8 for Syncing the subscription data of User
to an External Server . So it will be invoking when when a subscription is made
by the APIC Hook  **hook_apic_app_subscribe** and its done by creating custom module in Drupal 8 (Means inside developer Portal of APIC ). I have done all that but its causing error LIKE '**The website encountered an unexpected error. Please try again later'** when a subscription is made by  a user.
I don't why its occurring, How to Resolve it , and i think this is an issue.
I have done this thing before using Drupal 7 and that was successful.

**Comment by chrisdudley** [comment] 2020-03-04 12:00
Whats in the portal www pod web container log ?
That should give you more information on what the error was.

You can also enable extra development debug information from the admin UI - dont do it on production sites as it can give away confidential information but you can do it on a development site.

**Comment by chrisdudley** [comment] 2020-03-04 14:27
duplicate of https://github.com/ibm-apiconnect/devportal/issues/8

**Closed by chrisdudley** 2020-03-04 14:27 UTC
