### ISSUE TITLE
In correct message text. 'the' is twice in the sentence.

### ISSUE THREAD

**Issue by prashantsinalkar** [ibm-apiconnect/devportal#16] opened 2020-12-07 14:00 UTC
https://github.com/ibm-apiconnect/devportal/blob/733e7d29b36a8c9119cd6c3becc297d11343162f/auth_apic/src/Form/ApicUserLoginForm.php#L438

**Comment by redlanne** [comment] 2020-12-07 14:55
dupe of #15

**Closed by redlanne** 2020-12-07 14:55 UTC
