### ISSUE TITLE
hook_consumerorg_create not invoked on registration

### ISSUE THREAD

**Issue by elisherer** [ibm-apiconnect/devportal#6] opened 2019-09-11 11:55 UTC
When registering the hook `hook_consumerorg_create` is not invoked.
While creating a new organization from an existing developer does invoke it. This is needed to alter the organization entity (by adding additional fields to it)

**Comment by dineeno** [comment] 2019-09-17 12:54
Thanks for the issue, we'll take a look and update here when we have more information.

**Comment by elisherer** [comment] 2019-12-30 08:17
Hi,

Any update?

**Comment by chrisdudley** [comment] 2020-02-24 12:59
Apologies for the delay in responding - the hook code has been thoroughly reviewed recently and multiple issues have been fixed.
When testing this with the latest fixpack code which is due to be released in the next few weeks we could no longer reproduce the problem.
Please reopen if you still encounter issues after upgrading to 2018.4.1.10 (to be released in a couple of weeks).

**Closed by chrisdudley** 2020-02-24 12:59 UTC
